#include "DoorActor.h"
#include "TestHorrorGame/TestHorrorGameCharacter.h"
#include "Components/SphereComponent.h"
#include "Components/StaticMeshComponent.h"
#include "GameFramework/Character.h"
#include "InventoryComponent.h"
#include "Kismet/GameplayStatics.h"
#include "UObject/ConstructorHelpers.h"

ADoorActor::ADoorActor()
{
	PrimaryActorTick.bCanEverTick = false;

	DoorMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DoorMesh"));
	RootComponent = DoorMesh;

	// ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®ãƒ‰ã‚¢ãƒ¡ãƒƒã‚·ãƒ¥ã‚’è¨­å®š
	static ConstructorHelpers::FObjectFinder<UStaticMesh> DefaultDoorMesh(TEXT("/Game/PSXSurvivalHorrorFBX/PSXSurvivalHorrorFBX/MESH-Door"));
	if (DefaultDoorMesh.Succeeded())
	{
		
		DoorMesh->SetStaticMesh(DefaultDoorMesh.Object);
		UE_LOG(LogTemp, Warning, TEXT("âœ… Default door mesh assigned"));
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("âš ï¸ Could not find default door mesh"));
	}

	// ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®ãƒ‰ã‚¢ãƒãƒ†ãƒªã‚¢ãƒ«ã‚’è¨­å®š
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> DefaultDoorMaterial(TEXT("/Game/PSXSurvivalHorrorFBX/PSXSurvivalHorrorFBX/MAT-Door"));
	if (DefaultDoorMaterial.Succeeded())
	{
		DoorMesh->SetMaterial(0, DefaultDoorMaterial.Object);
		UE_LOG(LogTemp, Warning, TEXT("âœ… Default door material assigned"));
	}

	// ãƒ‰ã‚¢ãƒ¡ãƒƒã‚·ãƒ¥ã®ã‚³ãƒªã‚¸ãƒ§ãƒ³è¨­å®š
	DoorMesh->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	DoorMesh->SetCollisionResponseToAllChannels(ECR_Block);
	DoorMesh->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);

	InteractionSphere = CreateDefaultSubobject<USphereComponent>(TEXT("InteractionSphere"));
	InteractionSphere->SetupAttachment(RootComponent);
	InteractionSphere->SetSphereRadius(200.f);
	InteractionSphere->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	InteractionSphere->SetCollisionResponseToAllChannels(ECR_Ignore);
	InteractionSphere->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);

	bCanInteract = false;
	PlayerInRange = nullptr;

	RequiredKeyID = FName("key");
}

void ADoorActor::BeginPlay()
{
	Super::BeginPlay();
	
	InteractionSphere->OnComponentBeginOverlap.AddDynamic(this, &ADoorActor::OnOverlapBegin);
	InteractionSphere->OnComponentEndOverlap.AddDynamic(this, &ADoorActor::OnOverlapEnd);
}

void ADoorActor::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent,
								 AActor* OtherActor,
								 UPrimitiveComponent* OtherComp,
								 int32 OtherBodyIndex,
								 bool bFromSweep,
								 const FHitResult& SweepResult)
{
	ATestHorrorGameCharacter* Character = Cast<ATestHorrorGameCharacter>(OtherActor);
	if (Character && Character->IsPlayerControlled())
	{
		bCanInteract = true;
		PlayerInRange = Character;
		
		// ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆãƒªã‚¹ãƒˆã«è¿½åŠ 
		Character->InteractableDoors.AddUnique(this);
		
		UE_LOG(LogTemp, Warning, TEXT("ğŸšª ãƒ‰ã‚¢ãŒã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆå¯èƒ½ã«ãªã‚Šã¾ã—ãŸ"));
	}
}

void ADoorActor::OnOverlapEnd(UPrimitiveComponent* OverlappedComponent,
							   AActor* OtherActor,
							   UPrimitiveComponent* OtherComp,
							   int32 OtherBodyIndex)
{
	ATestHorrorGameCharacter* Character = Cast<ATestHorrorGameCharacter>(OtherActor);
	if (Character && Character == PlayerInRange)
	{
		bCanInteract = false;
		PlayerInRange = nullptr;
		
		// ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆãƒªã‚¹ãƒˆã‹ã‚‰å‰Šé™¤
		Character->InteractableDoors.Remove(this);
		
		UE_LOG(LogTemp, Warning, TEXT("ğŸšª ãƒ‰ã‚¢ãŒã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆç¯„å›²å¤–ã«ãªã‚Šã¾ã—ãŸ"));
	}
}

void ADoorActor::Interact(ACharacter* Character)
{
	if (!bCanInteract || !Character || Character != PlayerInRange)
	{
		return;
	}

	UInventoryComponent* Inventory = Character->FindComponentByClass<UInventoryComponent>();
	if (!Inventory)
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ ã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“"));
		return;
	}

	if (Inventory->HasItem(RequiredKeyID))
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ‰ éµã‚’æŒã£ã¦ã„ã¾ã™ï¼ã‚²ãƒ¼ãƒ ã‚¯ãƒªã‚¢ï¼"));
		GameClear();
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ”’ éµãŒå¿…è¦ã§ã™"));
	}
}

void ADoorActor::GameClear()
{
	UE_LOG(LogTemp, Warning, TEXT("ğŸ† ã‚²ãƒ¼ãƒ ã‚¯ãƒªã‚¢ï¼"));
	
	if (APlayerController* PC = UGameplayStatics::GetPlayerController(GetWorld(), 0))
	{
		PC->SetShowMouseCursor(true);
		
		FInputModeUIOnly InputMode;
		PC->SetInputMode(InputMode);
		
		UGameplayStatics::OpenLevel(GetWorld(), FName("MainMenuMap"));
		
		UE_LOG(LogTemp, Warning, TEXT("âœ… ã‚²ãƒ¼ãƒ ã‚¯ãƒªã‚¢å‡¦ç†å®Œäº† - ã‚¿ã‚¤ãƒˆãƒ«ç”»é¢ã«æˆ»ã‚Šã¾ã™"));
	}
}