#include "EnemyCharacter.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimEnums.h"
#include "Engine/Engine.h"
#include "Engine/DamageEvents.h"
#include "../TestHorrorGameCharacter.h"

AEnemyCharacter::AEnemyCharacter()
{
	PrimaryActorTick.bCanEverTick = true;

	// ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆè¨­å®š
	WalkSpeed = 200.0f;
	ChaseSpeed = 450.0f;
	AttackRange = 150.0f; // å¯†ç€æ”»æ’ƒç”¨ã«ç¸®å°
	AttackDamage = 20.0f;
	AttackCooldown = 3.0f; // ã‚¯ãƒ¼ãƒ«ãƒ€ã‚¦ãƒ³ã‚’3ç§’ã«å»¶é•·
	PatrolWaitTime = 3.0f;

	// åˆæœŸçŠ¶æ…‹
	CurrentState = EEnemyState::Idle;
	TargetPlayer = nullptr;
	bCanAttack = false;
	LastAttackTime = 0.0f;

	// Character Movementè¨­å®š
	GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;
	GetCharacterMovement()->bOrientRotationToMovement = true;
	GetCharacterMovement()->RotationRate = FRotator(0.0f, 300.0f, 0.0f);
	
	// Root Motionç„¡åŠ¹åŒ–ï¼ˆä½ç½®ãšã‚Œé˜²æ­¢ï¼‰
	// UE5.5ã§ã¯AnimBPã§è¨­å®šã™ã‚‹ãŸã‚ã€ã“ã“ã§ã¯ã‚³ãƒ¡ãƒ³ãƒˆã‚¢ã‚¦ãƒˆ
	// GetMesh()->SetRootMotionMode(ERootMotionMode::IgnoreRootMotion);

	// ã‚³ãƒªã‚¸ãƒ§ãƒ³è¨­å®š
	GetCapsuleComponent()->SetCollisionProfileName(TEXT("Pawn"));

	// ãƒ¡ãƒƒã‚·ãƒ¥ã®å‘ãã‚’ä¿®æ­£ï¼ˆSurvivorBã¯90åº¦å›è»¢ãŒå¿…è¦ï¼‰
	GetMesh()->SetRelativeRotation(FRotator(0.0f, -90.0f, 0.0f));
	

	// AIControllerã‚’è¨­å®š
	AIControllerClass = AEnemyAIController::StaticClass();
}

void AEnemyCharacter::BeginPlay()
{
	Super::BeginPlay();
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸ‘¹ EnemyCharacter spawned: %s"), *GetName());
	
	// åˆæœŸãƒ‘ãƒˆãƒ­ãƒ¼ãƒ«ãƒã‚¤ãƒ³ãƒˆè¨­å®šï¼ˆãƒ¬ãƒ™ãƒ«ã«é…ç½®ã•ã‚Œã¦ã„ãªã„å ´åˆï¼‰
	if (PatrolPoints.Num() == 0)
	{
		FVector CurrentLocation = GetActorLocation();
		PatrolPoints.Add(CurrentLocation + FVector(500.0f, 0.0f, 0.0f));
		PatrolPoints.Add(CurrentLocation + FVector(0.0f, 500.0f, 0.0f));
		PatrolPoints.Add(CurrentLocation + FVector(-500.0f, 0.0f, 0.0f));
		PatrolPoints.Add(CurrentLocation + FVector(0.0f, -500.0f, 0.0f));
	}
}

void AEnemyCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	
	// åŸºæœ¬çš„ãªãƒ‡ãƒãƒƒã‚°æƒ…å ±ï¼ˆæ¯ãƒ•ãƒ¬ãƒ¼ãƒ ï¼‰
	static int32 TickCount = 0;
	if (++TickCount % 120 == 0) // 2ç§’ãŠãã«è¡¨ç¤º
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ EnemyCharacter Tick - TargetPlayer: %s, CurrentState: %s"), 
			TargetPlayer ? TEXT("FOUND") : TEXT("NONE"), 
			*UEnum::GetValueAsString(CurrentState));
	}

	// ã‚¿ãƒ¼ã‚²ãƒƒãƒˆãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®å–å¾—ã¨çŠ¶æ…‹æ›´æ–°
	if (AEnemyAIController* AIController = Cast<AEnemyAIController>(GetController()))
	{
		TargetPlayer = AIController->GetTargetPlayer();
		
		// AI Controllerã®blackboardã‹ã‚‰çŠ¶æ…‹ã‚’åŒæœŸ
		if (UBlackboardComponent* BlackboardComp = AIController->GetBlackboardComponent())
		{
			bool bIsChasing = BlackboardComp->GetValueAsBool(TEXT("IsChasing"));
			bool bCanAttackBB = BlackboardComp->GetValueAsBool(TEXT("CanAttack"));
			
			// çŠ¶æ…‹ã‚’æ›´æ–°
			if (bIsChasing && TargetPlayer)
			{
				if (CurrentState != EEnemyState::Chasing && CurrentState != EEnemyState::Attacking)
				{
					SetEnemyState(EEnemyState::Chasing);
				}
			}
			else if (!bIsChasing && CurrentState == EEnemyState::Chasing)
			{
				SetEnemyState(EEnemyState::Idle);
			}
			
			// ãƒ‡ãƒãƒƒã‚°ãƒ­ã‚°ã‚’æ¸›ã‚‰ã™ï¼ˆå¿…è¦æ™‚ã®ã¿è¡¨ç¤ºï¼‰
			// UE_LOG(LogTemp, Warning, TEXT("ğŸ”„ State Sync - BB_IsChasing: %s, BB_CanAttack: %s, CurrentState: %s"), 
			//	bIsChasing ? TEXT("YES") : TEXT("NO"), 
			//	bCanAttackBB ? TEXT("YES") : TEXT("NO"), 
			//	*UEnum::GetValueAsString(CurrentState));
		}
	}

	// æ”»æ’ƒå¯èƒ½ã‹ãƒã‚§ãƒƒã‚¯
	bCanAttack = CanPerformAttack();
	
	// ãƒ‡ãƒãƒƒã‚°æƒ…å ±ã‚’è¿½åŠ 
	if (TargetPlayer && CurrentState == EEnemyState::Chasing)
	{
		float Distance = GetDistanceToPlayer();
		UE_LOG(LogTemp, Warning, TEXT("ğŸ” Debug - Distance: %.1f, bCanAttack: %s, CurrentState: %s"), 
			Distance, bCanAttack ? TEXT("YES") : TEXT("NO"), *UEnum::GetValueAsString(CurrentState));
	}
	
	// ãƒ†ã‚¹ãƒˆç”¨ã®ç°¡å˜ãªæ”»æ’ƒã‚³ãƒ¼ãƒ‰ã‚’å‰Šé™¤ï¼ˆæ­£å¸¸ã«å‹•ä½œã™ã‚‹ãŸã‚ï¼‰
	// if (TargetPlayer)
	// {
	//     float Distance = GetDistanceToPlayer();
	//     if (Distance <= 500.0f)
	//     {
	//         UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ SIMPLE ATTACK TEST - Distance: %.1f"), Distance);
	//         PerformAttack();
	//     }
	// }
	
	// è¦–ç•Œå†…ã«ã„ã‚‹é–“ã¯å¸¸ã«ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®ä½ç½®ã‚’è¿½è·¡ï¼ˆæ”»æ’ƒæ™‚ä»¥å¤–ï¼‰
	if (TargetPlayer && CurrentState != EEnemyState::Attacking)
	{
		// AIControllerã®Blackboardã‚’é€šã˜ã¦æœ€æ–°ã®ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ä½ç½®ã‚’æ›´æ–°
		if (AEnemyAIController* AIController = Cast<AEnemyAIController>(GetController()))
		{
			if (UBlackboardComponent* BlackboardComp = AIController->GetBlackboardComponent())
			{
				// ç¾åœ¨ã®è·é›¢ã‚’è¨ˆç®—
				float CurrentDistance = GetDistanceToPlayer();
				FVector PlayerCurrentLocation = TargetPlayer->GetActorLocation();
				
				// ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®ä½ç½®ã‚’å¸¸ã«æ›´æ–°
				BlackboardComp->SetValueAsVector(TEXT("LastKnownLocation"), PlayerCurrentLocation);
				
				// è¿½è·¡çŠ¶æ…‹ãªã‚‰ç›´æ¥ç§»å‹•æŒ‡ç¤ºã‚’å‡ºã™
				if (CurrentState == EEnemyState::Chasing)
				{
					AIController->MoveToLocation(PlayerCurrentLocation, 50.0f, true, true, true, true);
				}
				
				// æ”»æ’ƒè·é›¢å†…ã‹ã©ã†ã‹ã‚’å¸¸ã«æ›´æ–°
				BlackboardComp->SetValueAsBool(TEXT("CanAttack"), CurrentDistance <= AttackRange);
				
				// æ”»æ’ƒå¯èƒ½ãªå ´åˆã®ã¿æ”»æ’ƒã‚’å®Ÿè¡Œ
				if (bCanAttack && CurrentState == EEnemyState::Chasing)
				{
					UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ About to perform attack! Distance: %.1f"), CurrentDistance);
					PerformAttack();
				}
			}
		}
	}

	// ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³çŠ¶æ…‹ã‚’æ›´æ–°
	UpdateAnimationState();

	// ãƒ‡ãƒãƒƒã‚°æƒ…å ±ã¯ç„¡åŠ¹åŒ–
}

void AEnemyCharacter::SetEnemyState(EEnemyState NewState)
{
	if (CurrentState == NewState) return;

	// ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®æœ‰åŠ¹æ€§ã‚’ç¢ºèª
	if (!IsValid(this) || !GetCharacterMovement())
	{
		return;
	}

	EEnemyState PreviousState = CurrentState;
	CurrentState = NewState;

	// çŠ¶æ…‹å¤‰æ›´æ™‚ã®å‡¦ç†
	switch (NewState)
	{
		case EEnemyState::Idle:
			GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;
			break;

		case EEnemyState::Patrolling:
			GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;
			break;

		case EEnemyState::Chasing:
			GetCharacterMovement()->MaxWalkSpeed = ChaseSpeed;
			break;

		case EEnemyState::Attacking:
			GetCharacterMovement()->MaxWalkSpeed = 0.0f; // æ”»æ’ƒä¸­ã¯åœæ­¢
			break;

		case EEnemyState::Stunned:
			GetCharacterMovement()->MaxWalkSpeed = 0.0f; // ã‚¹ã‚¿ãƒ³ä¸­ã¯åœæ­¢
			break;
	}
}

void AEnemyCharacter::PerformAttack()
{
	if (!CanPerformAttack()) return;

	SetEnemyState(EEnemyState::Attacking);
	LastAttackTime = GetWorld()->GetTimeSeconds();

	UE_LOG(LogTemp, Warning, TEXT("âš”ï¸ Enemy starting attack animation!"));

	// æ”»æ’ƒã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³ã®é€”ä¸­ã§ãƒ€ãƒ¡ãƒ¼ã‚¸ã‚’ä¸ãˆã‚‹ï¼ˆã‚¿ã‚¤ãƒãƒ¼ã§å®Ÿè£…ï¼‰
	FTimerHandle AttackDamageTimer;
	GetWorld()->GetTimerManager().SetTimer(AttackDamageTimer, [this]()
	{
		// ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®æœ‰åŠ¹æ€§ç¢ºèª
		if (!IsValid(this)) return;
		
		// ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³ä¸­ã«ãƒ€ãƒ¡ãƒ¼ã‚¸ã‚’ä¸ãˆã‚‹
		if (TargetPlayer && CurrentState == EEnemyState::Attacking)
		{
			DealDamageToPlayer(TargetPlayer);
		}
	}, 0.8f, false);

	// ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³å®Ÿè¡Œå¾Œã«ãƒã‚§ã‚¤ã‚¹çŠ¶æ…‹ã«æˆ»ã‚‹ï¼ˆã‚¿ã‚¤ãƒãƒ¼ã§å®Ÿè£…ï¼‰
	FTimerHandle AttackEndTimer;
	GetWorld()->GetTimerManager().SetTimer(AttackEndTimer, [this]()
	{
		// ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã®æœ‰åŠ¹æ€§ç¢ºèª
		if (!IsValid(this)) return;
		
		SetEnemyState(EEnemyState::Chasing);
	}, 1.5f, false);
}

void AEnemyCharacter::DealDamageToPlayer(AActor* Player)
{
	if (!Player) return;

	// ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã«ãƒ€ãƒ¡ãƒ¼ã‚¸ã‚’ä¸ãˆã‚‹å‡¦ç†
	if (ATestHorrorGameCharacter* HorrorPlayer = Cast<ATestHorrorGameCharacter>(Player))
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ’¥ Enemy dealing %.1f damage to player!"), AttackDamage);
		
		// ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®ãƒ€ãƒ¡ãƒ¼ã‚¸å‡¦ç†ã‚’å®Ÿè¡Œ - ãƒ›ãƒ©ãƒ¼ã‚²ãƒ¼ãƒ ãªã®ã§å³æ­»
		FDamageEvent DamageEvent;
		HorrorPlayer->TakeDamage(AttackDamage, DamageEvent, GetController(), this);
		
		// è¦–è¦šåŠ¹æœã‚„ã‚µã‚¦ãƒ³ãƒ‰å†ç”Ÿã‚‚ã“ã“ã§å®Ÿè£…å¯èƒ½
		UE_LOG(LogTemp, Error, TEXT("ğŸ¯ Player has been attacked! Game should be over now."));
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Player cast failed - cannot deal damage"));
	}
}

float AEnemyCharacter::GetDistanceToPlayer() const
{
	if (!TargetPlayer) return -1.0f;

	return FVector::Dist(GetActorLocation(), TargetPlayer->GetActorLocation());
}

UHorrorCharacterAnimInstance* AEnemyCharacter::GetHorrorAnimInstance() const
{
	return Cast<UHorrorCharacterAnimInstance>(GetMesh()->GetAnimInstance());
}

void AEnemyCharacter::DebugCurrentState() const
{
	UE_LOG(LogTemp, Warning, TEXT("ğŸ‘¹ Enemy Debug - State: %s, Target: %s, Can Attack: %s"), 
		*UEnum::GetValueAsString(CurrentState),
		TargetPlayer ? *TargetPlayer->GetName() : TEXT("None"),
		bCanAttack ? TEXT("Yes") : TEXT("No"));
}

bool AEnemyCharacter::CanPerformAttack() const
{
	if (!TargetPlayer) 
	{
		return false;
	}
	if (CurrentState == EEnemyState::Attacking || CurrentState == EEnemyState::Stunned) 
	{
		return false;
	}
	
	float Distance = GetDistanceToPlayer();
	bool bInRange = Distance <= AttackRange && Distance > 0.0f;
	bool bCooldownReady = GetWorld()->GetTimeSeconds() - LastAttackTime >= AttackCooldown;

	// ãƒ‡ãƒãƒƒã‚°æƒ…å ±ã‚’æ¸›ã‚‰ã—ã¦ã€é‡è¦ãªæƒ…å ±ã®ã¿è¡¨ç¤º
	if (!bCooldownReady)
	{
		float RemainingCooldown = AttackCooldown - (GetWorld()->GetTimeSeconds() - LastAttackTime);
		UE_LOG(LogTemp, Warning, TEXT("â° Attack cooldown: %.1f seconds remaining"), RemainingCooldown);
	}

	return bInRange && bCooldownReady;
}

void AEnemyCharacter::UpdateAnimationState()
{
	UHorrorCharacterAnimInstance* AnimInstance = GetHorrorAnimInstance();
	if (!AnimInstance) 
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ AnimInstance is null in UpdateAnimationState"));
		return;
	}

	// ç§»å‹•é€Ÿåº¦ã‚’å–å¾—
	FVector Velocity = GetVelocity();
	float CurrentSpeed = Velocity.Size();
	
	// æ—¢å­˜ã®ãƒ—ãƒ­ãƒ‘ãƒ†ã‚£ã«ç›´æ¥å€¤ã‚’è¨­å®š
	AnimInstance->Speed = CurrentSpeed;
	AnimInstance->bIsMoving = CurrentSpeed > 5.0f; // 5ãƒ¦ãƒ‹ãƒƒãƒˆ/ç§’ä»¥ä¸Šã§ç§»å‹•ä¸­ï¼ˆé–¾å€¤ã‚’ä¸‹ã’ã‚‹ï¼‰

	// ãƒ‡ãƒãƒƒã‚°ãƒ­ã‚°ã‚’è¿½åŠ  - ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³å€¤ã®ç¢ºèª
	static int32 AnimDebugCount = 0;
	if (++AnimDebugCount % 60 == 0) // 1ç§’ãŠãã«è¡¨ç¤º
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ¬ Animation Debug - Speed: %.2f, bIsMoving: %s, CurrentState: %s"), 
			CurrentSpeed, 
			AnimInstance->bIsMoving ? TEXT("TRUE") : TEXT("FALSE"),
			*UEnum::GetValueAsString(CurrentState));
	}

	// æ•µã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ã‚¢ã‚¯ã‚·ãƒ§ãƒ³çŠ¶æ…‹ã‚’è¨­å®š
	switch (CurrentState)
	{
		case EEnemyState::Idle:
			// ã‚¢ã‚¤ãƒ‰ãƒ«çŠ¶æ…‹ - ç§»å‹•é€Ÿåº¦ã§è‡ªå‹•åˆ¤å®šã•ã‚Œã‚‹
			AnimInstance->SetActionState(EHorrorActionState::None);
			break;

		case EEnemyState::Patrolling:
		case EEnemyState::Chasing:
			// ç§»å‹•ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³ - ç§»å‹•é€Ÿåº¦ã§è‡ªå‹•åˆ¤å®šã•ã‚Œã‚‹
			AnimInstance->SetActionState(EHorrorActionState::None);
			break;

		case EEnemyState::Attacking:
			// æ”»æ’ƒã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³
			AnimInstance->SetActionState(EHorrorActionState::Interacting);
			break;

		case EEnemyState::Stunned:
			// ã‚¹ã‚¿ãƒ³ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³
			AnimInstance->SetActionState(EHorrorActionState::Grabbed);
			break;
	}
}