#include "GameOverWidget.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/GameModeBase.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Engine/Engine.h"

void UGameOverWidget::NativeConstruct()
{
    Super::NativeConstruct();
    
    // ãƒœã‚¿ãƒ³ã®ã‚¤ãƒ™ãƒ³ãƒˆã‚’ãƒã‚¤ãƒ³ãƒ‰
    if (RestartButton)
    {
        RestartButton->OnClicked.AddDynamic(this, &UGameOverWidget::OnRestartButtonClicked);
    }
    
    if (MainMenuButton)
    {
        MainMenuButton->OnClicked.AddDynamic(this, &UGameOverWidget::OnMainMenuButtonClicked);
    }
    
    if (QuitButton)
    {
        QuitButton->OnClicked.AddDynamic(this, &UGameOverWidget::OnQuitButtonClicked);
    }
    
    // ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼ãƒ†ã‚­ã‚¹ãƒˆã‚’è¨­å®š
    if (GameOverText)
    {
        GameOverText->SetText(FText::FromString(TEXT("ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼")));
    }
    
    UE_LOG(LogTemp, Warning, TEXT("ðŸ’€ GameOverWidget constructed successfully"));
}

void UGameOverWidget::NativeDestruct()
{
    // ãƒ‡ãƒªã‚²ãƒ¼ãƒˆã‚’å®‰å…¨ã«ã‚¢ãƒ³ãƒã‚¤ãƒ³ãƒ‰
    if (RestartButton)
    {
        RestartButton->OnClicked.RemoveAll(this);
    }
    
    if (MainMenuButton)
    {
        MainMenuButton->OnClicked.RemoveAll(this);
    }
    
    if (QuitButton)
    {
        QuitButton->OnClicked.RemoveAll(this);
    }
    
    Super::NativeDestruct();
}

void UGameOverWidget::ShowGameOver()
{
    UE_LOG(LogTemp, Warning, TEXT("ðŸ’€ Showing Game Over screen"));
    
    // ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’ãƒ“ãƒ¥ãƒ¼ãƒãƒ¼ãƒˆã«è¿½åŠ 
    AddToViewport();
    
    // ãƒžã‚¦ã‚¹ã‚«ãƒ¼ã‚½ãƒ«ã‚’è¡¨ç¤ºã—ã¦UIãƒ¢ãƒ¼ãƒ‰ã«è¨­å®š
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            PlayerController->bShowMouseCursor = true;
            PlayerController->SetInputMode(FInputModeUIOnly());
            
            // ã‚²ãƒ¼ãƒ ã‚’ä¸€æ™‚åœæ­¢
            PlayerController->SetPause(true);
            
            UE_LOG(LogTemp, Warning, TEXT("ðŸŽ® Game Over UI mode activated"));
        }
    }
}

void UGameOverWidget::OnRestartButtonClicked()
{
    UE_LOG(LogTemp, Warning, TEXT("ðŸ”„ Restart button clicked"));
    
    // ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼ç”»é¢ã‚’å‰Šé™¤
    RemoveFromParent();
    
    // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’æ­£å¸¸ã«æˆ»ã—ã¦ã‹ã‚‰ãƒ¬ãƒ™ãƒ«ã‚’ãƒªãƒ­ãƒ¼ãƒ‰
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            // ã‚²ãƒ¼ãƒ ã‚’å†é–‹
            PlayerController->SetPause(false);
            
            // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ã‚²ãƒ¼ãƒ ãƒ¢ãƒ¼ãƒ‰ã«æˆ»ã™
            PlayerController->bShowMouseCursor = false;
            PlayerController->SetInputMode(FInputModeGameOnly());
            
            UE_LOG(LogTemp, Warning, TEXT("ðŸŽ® Input mode restored to Game Only"));
        }
        
        // ç¾åœ¨ã®ãƒ¬ãƒ™ãƒ«åã‚’å–å¾—ã—ã¦ãƒªãƒ­ãƒ¼ãƒ‰
        FString CurrentLevelName = World->GetMapName();
        CurrentLevelName = CurrentLevelName.Replace(TEXT("UEDPIE_0_"), TEXT("")); // ã‚¨ãƒ‡ã‚£ã‚¿ç”¨ãƒ—ãƒ¬ãƒ•ã‚£ãƒƒã‚¯ã‚¹ã‚’å‰Šé™¤
        
        UE_LOG(LogTemp, Warning, TEXT("ðŸ”„ Restarting level: %s"), *CurrentLevelName);
        UGameplayStatics::OpenLevel(this, FName(*CurrentLevelName));
    }
}

void UGameOverWidget::OnMainMenuButtonClicked()
{
    UE_LOG(LogTemp, Warning, TEXT("ðŸ  Main Menu button clicked"));
    
    // ã‚²ãƒ¼ãƒ ã‚ªãƒ¼ãƒãƒ¼ç”»é¢ã‚’å‰Šé™¤
    RemoveFromParent();
    
    // ã‚²ãƒ¼ãƒ ã‚’å†é–‹ã—ã¦ã‹ã‚‰ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ãƒ¬ãƒ™ãƒ«ã«ç§»å‹•
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            PlayerController->SetPause(false);
            
            // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’UIãƒ¢ãƒ¼ãƒ‰ã«è¨­å®šï¼ˆãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ç”¨ï¼‰
            PlayerController->bShowMouseCursor = true;
            PlayerController->SetInputMode(FInputModeUIOnly());
            
            UE_LOG(LogTemp, Warning, TEXT("ðŸŽ® Input mode set to UI Only for Main Menu"));
        }
        
        // ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ãƒ¬ãƒ™ãƒ«ã‚’é–‹ã
        UE_LOG(LogTemp, Warning, TEXT("ðŸ  Loading MainMenu level..."));
        UGameplayStatics::OpenLevel(this, TEXT("MainMenu"));
    }
}

void UGameOverWidget::OnQuitButtonClicked()
{
    UE_LOG(LogTemp, Warning, TEXT("ðŸšª Quit button clicked"));
    
    // ã‚²ãƒ¼ãƒ ã‚’çµ‚äº†
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            PlayerController->SetPause(false);
            
            // ã‚²ãƒ¼ãƒ ã‚’çµ‚äº†
            UKismetSystemLibrary::QuitGame(World, PlayerController, EQuitPreference::Quit, false);
        }
    }
}