#include "ItemActor.h"
#include "TestHorrorGame/TestHorrorGameCharacter.h"
#include "Components/SphereComponent.h"
#include "Components/StaticMeshComponent.h"
#include "GameFramework/Character.h"
#include "InventoryComponent.h"
#include "UObject/ConstructorHelpers.h"

AItemActor::AItemActor()
{
	PrimaryActorTick.bCanEverTick = false;

	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	RootComponent = Mesh;

	PickupSphere = CreateDefaultSubobject<USphereComponent>(TEXT("PickupSphere"));
	PickupSphere->SetupAttachment(RootComponent);
	PickupSphere->SetSphereRadius(250.f);  // æœºã®ä¸Šã®ã‚¢ã‚¤ãƒ†ãƒ ç”¨ã«å¤§ãã‚ã«
	PickupSphere->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	PickupSphere->SetCollisionResponseToAllChannels(ECR_Ignore);
	PickupSphere->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
	PickupSphere->SetCollisionResponseToChannel(ECC_WorldStatic, ECR_Ignore);  // æœºãªã©ã®é™çš„ãƒ¡ãƒƒã‚·ãƒ¥ã‚’ç„¡è¦–

	bCanInteract = false;
	PlayerInRange = nullptr;

	// ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®ã‚¢ã‚¤ãƒ†ãƒ ãƒ‡ãƒ¼ã‚¿ã‚’è¨­å®šï¼ˆãƒ†ã‚¹ãƒˆç”¨ï¼‰
	ItemData.ItemID = FName("DefaultItem");
	ItemData.Name = FText::FromString("ãƒ†ã‚¹ãƒˆã‚¢ã‚¤ãƒ†ãƒ ");
	ItemData.Description = FText::FromString("ã“ã‚Œã¯ãƒ†ã‚¹ãƒˆç”¨ã®ã‚¢ã‚¤ãƒ†ãƒ ã§ã™ã€‚èª¬æ˜ãŒã“ã“ã«è¡¨ç¤ºã•ã‚Œã¾ã™ã€‚");
	ItemData.MaxStack = 99;
	ItemData.Icon = nullptr; // ã‚¢ã‚¤ã‚³ãƒ³ã¯ãƒ–ãƒ«ãƒ¼ãƒ—ãƒªãƒ³ãƒˆã§è¨­å®š
	
	// ãƒ†ã‚¹ãƒˆç”¨ï¼šãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã‚­ãƒ¥ãƒ¼ãƒ–ãƒ¡ãƒƒã‚·ãƒ¥ã‚’ä½¿ç”¨
	static ConstructorHelpers::FObjectFinder<UStaticMesh> DefaultMesh(TEXT("/Engine/BasicShapes/Cube"));
	if (DefaultMesh.Succeeded())
	{
		ItemData.Mesh = DefaultMesh.Object;
		UE_LOG(LogTemp, Warning, TEXT("âœ… Default cube mesh assigned for testing"));
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("âš ï¸ Could not find default cube mesh"));
	}
}

void AItemActor::BeginPlay()
{
	Super::BeginPlay();

	PickupSphere->OnComponentBeginOverlap.AddDynamic(this, &AItemActor::OnOverlapBegin);
	PickupSphere->OnComponentEndOverlap.AddDynamic(this, &AItemActor::OnOverlapEnd);
	
	// ãƒ‡ãƒãƒƒã‚°ç”¨ï¼šã‚³ãƒªã‚¸ãƒ§ãƒ³çƒã‚’å¯è¦–åŒ–ï¼ˆé–‹ç™ºä¸­ã®ã¿ï¼‰
	#if WITH_EDITOR
	PickupSphere->SetHiddenInGame(false);
	PickupSphere->SetVisibility(true);
	UE_LOG(LogTemp, Warning, TEXT("ğŸ” ã‚¢ã‚¤ãƒ†ãƒ ã€Œ%sã€ã®PickupSphereåŠå¾„: %.1f"), *ItemData.Name.ToString(), PickupSphere->GetScaledSphereRadius());
	#endif
}

void AItemActor::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent,
								 AActor* OtherActor,
								 UPrimitiveComponent* OtherComp,
								 int32 OtherBodyIndex,
								 bool bFromSweep,
								 const FHitResult& SweepResult)
{
	ATestHorrorGameCharacter* Character = Cast<ATestHorrorGameCharacter>(OtherActor);
	if (Character && Character->IsPlayerControlled())
	{
		bCanInteract = true;
		PlayerInRange = Character;
		
		// ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆãƒªã‚¹ãƒˆã«è¿½åŠ 
		Character->InteractableItems.AddUnique(this);
		
		// ãƒ‡ãƒãƒƒã‚°æƒ…å ±ã‚’è¿½åŠ 
		float Distance = FVector::Dist(GetActorLocation(), Character->GetActorLocation());
		UE_LOG(LogTemp, Warning, TEXT("ğŸ”‘ ã‚¢ã‚¤ãƒ†ãƒ ã€Œ%sã€ãŒã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆå¯èƒ½ã«ãªã‚Šã¾ã—ãŸ (è·é›¢: %.1f)"), *ItemData.Name.ToString(), Distance);
		UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ ã‚¢ã‚¤ãƒ†ãƒ ä½ç½®: %s, ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ä½ç½®: %s"), 
			*GetActorLocation().ToString(), *Character->GetActorLocation().ToString());
	}
}

void AItemActor::OnOverlapEnd(UPrimitiveComponent* OverlappedComponent,
							   AActor* OtherActor,
							   UPrimitiveComponent* OtherComp,
							   int32 OtherBodyIndex)
{
	ATestHorrorGameCharacter* Character = Cast<ATestHorrorGameCharacter>(OtherActor);
	if (Character && Character == PlayerInRange)
	{
		bCanInteract = false;
		PlayerInRange = nullptr;
		
		// ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆãƒªã‚¹ãƒˆã‹ã‚‰å‰Šé™¤
		Character->InteractableItems.Remove(this);
		
		// UIã®ã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆè¡¨ç¤ºã‚’éè¡¨ç¤ºã«
		UE_LOG(LogTemp, Warning, TEXT("ã‚¢ã‚¤ãƒ†ãƒ ãŒã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ãƒˆç¯„å›²å¤–ã«ãªã‚Šã¾ã—ãŸ"));
	}
}

void AItemActor::Interact(ACharacter* Character)
{
	if (!bCanInteract || !Character || Character != PlayerInRange)
	{
		return;
	}

	// ãƒ‡ãƒãƒƒã‚°ï¼šé€ä¿¡ã™ã‚‹ã‚¢ã‚¤ãƒ†ãƒ ãƒ‡ãƒ¼ã‚¿ã‚’ç¢ºèª
	UE_LOG(LogTemp, Warning, TEXT("ğŸ® ItemActor::Interact - Sending item data:"));
	UE_LOG(LogTemp, Warning, TEXT("ğŸ“‹ ItemID: %s"), *ItemData.ItemID.ToString());
	UE_LOG(LogTemp, Warning, TEXT("ğŸ“‹ Name: %s"), *ItemData.Name.ToString());
	UE_LOG(LogTemp, Warning, TEXT("ğŸ“‹ Description: %s"), *ItemData.Description.ToString());
	UE_LOG(LogTemp, Warning, TEXT("ğŸ“‹ MaxStack: %d"), ItemData.MaxStack);

	UInventoryComponent* Inventory = Character->FindComponentByClass<UInventoryComponent>();
	if (Inventory)
	{
		bool bSuccess = Inventory->AddItem(ItemData, 1);
		if (bSuccess)
		{
			UE_LOG(LogTemp, Warning, TEXT("ã‚¢ã‚¤ãƒ†ãƒ ã€Œ%sã€ã‚’å–å¾—ã—ã¾ã—ãŸï¼"), *ItemData.Name.ToString());
			Destroy(); // æ‹¾ã‚ã‚ŒãŸã®ã§æ¶ˆã™
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("ã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªãŒã„ã£ã±ã„ã§ã™ï¼"));
		}
	}
}
