#include "MainMenuGameMode.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "Blueprint/UserWidget.h"

AMainMenuGameMode::AMainMenuGameMode()
{
    // ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã§ã¯ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚’ç„¡åŠ¹åŒ–
    DefaultPawnClass = nullptr;
    
    // MainMenuWidgetã®åˆæœŸåŒ–
    MainMenuWidget = nullptr;
}

void AMainMenuGameMode::BeginPlay()
{
    Super::BeginPlay();
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ® MainMenuGameMode BeginPlay started"));
    
    // ç¾åœ¨ã®ãƒ¬ãƒ™ãƒ«åã‚’å–å¾—
    FString CurrentLevelName = GetWorld()->GetMapName();
    CurrentLevelName = CurrentLevelName.Replace(TEXT("UEDPIE_0_"), TEXT("")); // ã‚¨ãƒ‡ã‚£ã‚¿ç”¨ãƒ—ãƒ¬ãƒ•ã‚£ãƒƒã‚¯ã‚¹ã‚’å‰Šé™¤
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” Current level: %s"), *CurrentLevelName);
    
    // MainMenuãƒ¬ãƒ™ãƒ«ã§ã®ã¿ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’è¡¨ç¤º
    if (CurrentLevelName.Contains(TEXT("MainMenu")) || CurrentLevelName.Contains(TEXT("mainmenu")))
    {
        UE_LOG(LogTemp, Warning, TEXT("âœ… MainMenu level detected - showing menu widget"));
        
        // ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’è¡¨ç¤º
        if (MainMenuWidgetClass && !MainMenuWidget)
        {
            MainMenuWidget = CreateWidget<UMainMenuWidget>(GetWorld(), MainMenuWidgetClass);
            if (MainMenuWidget)
            {
                UE_LOG(LogTemp, Warning, TEXT("ğŸ® MainMenuWidget created successfully"));
                MainMenuWidget->ShowMainMenu();
            }
            else
            {
                UE_LOG(LogTemp, Error, TEXT("âŒ Failed to create MainMenuWidget"));
            }
        }
        else if (!MainMenuWidgetClass)
        {
            UE_LOG(LogTemp, Error, TEXT("âŒ MainMenuWidgetClass is not assigned in Blueprint"));
        }
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("â­ï¸ Not MainMenu level - skipping menu widget"));
    }
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ® MainMenuGameMode BeginPlay completed"));
}