#include "MainMenuWidget.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Engine/Engine.h"
#include "Blueprint/WidgetTree.h"

void UMainMenuWidget::NativeConstruct()
{
    Super::NativeConstruct();
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” MainMenuWidget NativeConstruct started"));
    
    // BindWidgetãŒå¤±æ•—ã—ãŸå ´åˆã®ä»£æ›¿æ‰‹æ®µã¨ã—ã¦æ‰‹å‹•ã§ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’æ¤œç´¢
    if (!StartGameButton)
    {
        // è¤‡æ•°ã®å¯èƒ½ãªåå‰ã§æ¤œç´¢
        TArray<FString> PossibleNames = {TEXT("StartGameButton"), TEXT("StartButton"), TEXT("Start")};
        for (const FString& Name : PossibleNames)
        {
            StartGameButton = Cast<UButton>(GetWidgetFromName(*Name));
            if (StartGameButton)
            {
                UE_LOG(LogTemp, Warning, TEXT("ğŸ” Found StartGameButton with name: %s"), *Name);
                break;
            }
        }
        
        // ãã‚Œã§ã‚‚è¦‹ã¤ã‹ã‚‰ãªã„å ´åˆã¯ã€ã™ã¹ã¦ã®Buttonã‚’æ¤œç´¢
        if (!StartGameButton)
        {
            TArray<UWidget*> AllChildren;
            WidgetTree->GetAllWidgets(AllChildren);
            for (UWidget* Child : AllChildren)
            {
                if (UButton* Button = Cast<UButton>(Child))
                {
                    FString ButtonName = Button->GetName();
                    if (ButtonName.Contains(TEXT("Start")) || ButtonName.Contains(TEXT("Game")))
                    {
                        StartGameButton = Button;
                        UE_LOG(LogTemp, Warning, TEXT("ğŸ” Found StartGameButton by search: %s"), *ButtonName);
                        break;
                    }
                }
            }
        }
    }
    
    if (!SettingsButton)
    {
        TArray<FString> PossibleNames = {TEXT("SettingsButton"), TEXT("Settings"), TEXT("Option")};
        for (const FString& Name : PossibleNames)
        {
            SettingsButton = Cast<UButton>(GetWidgetFromName(*Name));
            if (SettingsButton) break;
        }
        
        if (!SettingsButton)
        {
            TArray<UWidget*> AllChildren;
            WidgetTree->GetAllWidgets(AllChildren);
            for (UWidget* Child : AllChildren)
            {
                if (UButton* Button = Cast<UButton>(Child))
                {
                    FString ButtonName = Button->GetName();
                    if (ButtonName.Contains(TEXT("Setting")) || ButtonName.Contains(TEXT("Option")))
                    {
                        SettingsButton = Button;
                        break;
                    }
                }
            }
        }
    }
    
    if (!QuitButton)
    {
        TArray<FString> PossibleNames = {TEXT("QuitButton"), TEXT("Quit"), TEXT("Exit")};
        for (const FString& Name : PossibleNames)
        {
            QuitButton = Cast<UButton>(GetWidgetFromName(*Name));
            if (QuitButton) break;
        }
        
        if (!QuitButton)
        {
            TArray<UWidget*> AllChildren;
            WidgetTree->GetAllWidgets(AllChildren);
            for (UWidget* Child : AllChildren)
            {
                if (UButton* Button = Cast<UButton>(Child))
                {
                    FString ButtonName = Button->GetName();
                    if (ButtonName.Contains(TEXT("Quit")) || ButtonName.Contains(TEXT("Exit")))
                    {
                        QuitButton = Button;
                        break;
                    }
                }
            }
        }
    }
    
    if (!TitleText)
    {
        TArray<FString> PossibleNames = {TEXT("TitleText"), TEXT("Title"), TEXT("GameTitle")};
        for (const FString& Name : PossibleNames)
        {
            TitleText = Cast<UTextBlock>(GetWidgetFromName(*Name));
            if (TitleText) break;
        }
        
        if (!TitleText)
        {
            TArray<UWidget*> AllChildren;
            WidgetTree->GetAllWidgets(AllChildren);
            for (UWidget* Child : AllChildren)
            {
                if (UTextBlock* TextBlock = Cast<UTextBlock>(Child))
                {
                    FString TextName = TextBlock->GetName();
                    if (TextName.Contains(TEXT("Title")))
                    {
                        TitleText = TextBlock;
                        break;
                    }
                }
            }
        }
    }
    
    // å„ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã®å­˜åœ¨ãƒã‚§ãƒƒã‚¯
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” StartGameButton is %s"), StartGameButton ? TEXT("Valid") : TEXT("NULL"));
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” SettingsButton is %s"), SettingsButton ? TEXT("Valid") : TEXT("NULL"));
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” QuitButton is %s"), QuitButton ? TEXT("Valid") : TEXT("NULL"));
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” TitleText is %s"), TitleText ? TEXT("Valid") : TEXT("NULL"));
    
    // ãƒœã‚¿ãƒ³ã®ã‚¤ãƒ™ãƒ³ãƒˆã‚’ãƒã‚¤ãƒ³ãƒ‰
    if (StartGameButton)
    {
        StartGameButton->OnClicked.AddDynamic(this, &UMainMenuWidget::OnStartGameButtonClicked);
        UE_LOG(LogTemp, Warning, TEXT("âœ… StartGameButton event bound successfully"));
        
        // OnPressedã¨OnReleasedã‚‚ãƒã‚¤ãƒ³ãƒ‰ã—ã¦ãƒ†ã‚¹ãƒˆ
        StartGameButton->OnPressed.AddDynamic(this, &UMainMenuWidget::OnStartGameButtonPressed);
        StartGameButton->OnReleased.AddDynamic(this, &UMainMenuWidget::OnStartGameButtonReleased);
        
        // ãƒœã‚¿ãƒ³ã®çŠ¶æ…‹ã‚’ãƒã‚§ãƒƒã‚¯
        UE_LOG(LogTemp, Warning, TEXT("ğŸ” StartGameButton IsEnabled: %s"), StartGameButton->GetIsEnabled() ? TEXT("true") : TEXT("false"));
        UE_LOG(LogTemp, Warning, TEXT("ğŸ” StartGameButton Visibility: %d"), (int32)StartGameButton->GetVisibility());
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ StartGameButton is NULL - check Blueprint variable name"));
    }
    
    if (SettingsButton)
    {
        SettingsButton->OnClicked.AddDynamic(this, &UMainMenuWidget::OnSettingsButtonClicked);
        UE_LOG(LogTemp, Warning, TEXT("âœ… SettingsButton event bound successfully"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ SettingsButton is NULL"));
    }
    
    if (QuitButton)
    {
        QuitButton->OnClicked.AddDynamic(this, &UMainMenuWidget::OnQuitButtonClicked);
        UE_LOG(LogTemp, Warning, TEXT("âœ… QuitButton event bound successfully"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ QuitButton is NULL"));
    }
    
    // ã‚¿ã‚¤ãƒˆãƒ«ãƒ†ã‚­ã‚¹ãƒˆã‚’è¨­å®š
    if (TitleText)
    {
        TitleText->SetText(FText::FromString(TEXT("ãƒ›ãƒ©ãƒ¼ã‚²ãƒ¼ãƒ ")));
        UE_LOG(LogTemp, Warning, TEXT("âœ… TitleText set successfully"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ TitleText is NULL"));
    }
    
    UE_LOG(LogTemp, Warning, TEXT("ğŸ® MainMenuWidget constructed successfully"));
    
    // ãƒ‡ãƒãƒƒã‚°ç”¨ï¼šã™ã¹ã¦ã®ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆåã‚’å‡ºåŠ›
    DebugPrintAllWidgetNames();
}

void UMainMenuWidget::NativeDestruct()
{
    // ãƒ‡ãƒªã‚²ãƒ¼ãƒˆã‚’å®‰å…¨ã«ã‚¢ãƒ³ãƒã‚¤ãƒ³ãƒ‰
    if (StartGameButton)
    {
        StartGameButton->OnClicked.RemoveAll(this);
    }
    
    if (SettingsButton)
    {
        SettingsButton->OnClicked.RemoveAll(this);
    }
    
    if (QuitButton)
    {
        QuitButton->OnClicked.RemoveAll(this);
    }
    
    Super::NativeDestruct();
}

void UMainMenuWidget::ShowMainMenu()
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ® Showing Main Menu screen"));
    
    // ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’ãƒ“ãƒ¥ãƒ¼ãƒãƒ¼ãƒˆã«è¿½åŠ 
    AddToViewport();
    
    // ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã«ãƒ•ã‚©ãƒ¼ã‚«ã‚¹ã‚’è¨­å®š
    SetFocus();
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” Widget focus set"));
    
    // ãƒã‚¦ã‚¹ã‚«ãƒ¼ã‚½ãƒ«ã‚’è¡¨ç¤ºã—ã¦UIãƒ¢ãƒ¼ãƒ‰ã«è¨­å®š
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            PlayerController->bShowMouseCursor = true;
            PlayerController->SetInputMode(FInputModeUIOnly());
            
            UE_LOG(LogTemp, Warning, TEXT("ğŸ® Main Menu UI mode activated"));
            UE_LOG(LogTemp, Warning, TEXT("ğŸ” Mouse cursor visible: %s"), PlayerController->bShowMouseCursor ? TEXT("true") : TEXT("false"));
        }
    }
    
    // è¿½åŠ ã®ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆçŠ¶æ…‹ãƒã‚§ãƒƒã‚¯
    UE_LOG(LogTemp, Warning, TEXT("ğŸ” Widget IsInViewport: %s"), IsInViewport() ? TEXT("true") : TEXT("false"));
    
    if (UWorld* CurrentWorld = GetWorld())
    {
        if (APlayerController* PC = CurrentWorld->GetFirstPlayerController())
        {
            UE_LOG(LogTemp, Warning, TEXT("ğŸ” Widget HasUserFocus: %s"), HasUserFocus(PC) ? TEXT("true") : TEXT("false"));
        }
    }
}

void UMainMenuWidget::OnStartGameButtonPressed()
{
    // ãƒ­ã‚°å‰Šé™¤
}

void UMainMenuWidget::OnStartGameButtonReleased()
{
    // ãƒ­ã‚°å‰Šé™¤
}

void UMainMenuWidget::OnStartGameButtonClicked()
{
    // ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚’å‰Šé™¤
    RemoveFromParent();
    
    // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ã‚²ãƒ¼ãƒ ãƒ¢ãƒ¼ãƒ‰ã«æˆ»ã—ã¦ã‹ã‚‰ãƒ¡ã‚¤ãƒ³ã‚²ãƒ¼ãƒ ãƒ¬ãƒ™ãƒ«ã‚’ãƒ­ãƒ¼ãƒ‰
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            // å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰ã‚’ã‚²ãƒ¼ãƒ ãƒ¢ãƒ¼ãƒ‰ã«æˆ»ã™
            PlayerController->bShowMouseCursor = false;
            PlayerController->SetInputMode(FInputModeGameOnly());
        }
        
        // ãƒ¡ã‚¤ãƒ³ã‚²ãƒ¼ãƒ ãƒ¬ãƒ™ãƒ«(testWorld)ã‚’ãƒ­ãƒ¼ãƒ‰
        UGameplayStatics::OpenLevel(this, FName(*FString("testWorld")));
    }
}

void UMainMenuWidget::OnSettingsButtonClicked()
{
    // è¨­å®šç”»é¢ã®å®Ÿè£…ï¼ˆå°†æ¥çš„ã«å®Ÿè£…ï¼‰
}

void UMainMenuWidget::OnQuitButtonClicked()
{
    // ã‚²ãƒ¼ãƒ ã‚’çµ‚äº†
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            UKismetSystemLibrary::QuitGame(World, PlayerController, EQuitPreference::Quit, false);
        }
    }
}

void UMainMenuWidget::DebugPrintAllWidgetNames()
{
    // ãƒ‡ãƒãƒƒã‚°æ©Ÿèƒ½ã¯ç„¡åŠ¹åŒ–
}