#include "MenuWidget.h"
#include "Components/ScrollBox.h"
#include "Components/Image.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "MenuItemWidget.h"
#include "Engine/Texture2D.h"
#include "Engine/World.h"
#include "GameFramework/PlayerController.h"
#include "EnhancedInputSubsystems.h"
#include "Engine/LocalPlayer.h"
#include "TestHorrorGame/TestHorrorGameCharacter.h"
#include "ItemData.h"

void UMenuWidget::NativeConstruct()
{
    Super::NativeConstruct();
    
    // é–‰ã˜ã‚‹ãƒœã‚¿ãƒ³ã®ã‚¤ãƒ™ãƒ³ãƒˆã‚’ãƒã‚¤ãƒ³ãƒ‰
    if (CloseButton)
    {
        CloseButton->OnClicked.AddDynamic(this, &UMenuWidget::OnCloseButtonClicked);
    }
    
    // åˆæœŸçŠ¶æ…‹ã§ã¯è©³ç´°è¡¨ç¤ºã‚¨ãƒªã‚¢ã‚’ç©ºã«ã™ã‚‹
    if (DetailItemIcon)
    {
        DetailItemIcon->SetBrushFromTexture(nullptr);
    }
    if (DetailItemName)
    {
        DetailItemName->SetText(FText::FromString(TEXT("ã‚¢ã‚¤ãƒ†ãƒ ã‚’é¸æŠã—ã¦ãã ã•ã„")));
    }
    if (DetailItemDescription)
    {
        DetailItemDescription->SetText(FText::FromString(TEXT("")));
    }
    if (DetailItemCount)
    {
        DetailItemCount->SetText(FText::FromString(TEXT("")));
    }
}

void UMenuWidget::NativeDestruct()
{
    // ãƒ‡ãƒªã‚²ãƒ¼ãƒˆã‚’å®‰å…¨ã«ã‚¢ãƒ³ãƒã‚¤ãƒ³ãƒ‰
    if (CloseButton)
    {
        CloseButton->OnClicked.RemoveAll(this);
    }
    
    Super::NativeDestruct();
}

void UMenuWidget::SetInventory(const TArray<FInventorySlot>& Items)
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ“‹ MenuWidget: SetInventory called with %d items"), Items.Num());

    if (!ItemListScrollBox)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ ItemListScrollBox is null!"));
        return;
    }

    if (!MenuItemWidgetClass)
    {
        UE_LOG(LogTemp, Error, TEXT("âŒ MenuItemWidgetClass is null! Did you assign it in BP?"));
        return;
    }

    // æ—¢å­˜ã®ã‚¢ã‚¤ãƒ†ãƒ ã‚’å®‰å…¨ã«ã‚¯ãƒªã‚¢
    if (ItemListScrollBox->GetChildrenCount() > 0)
    {
        // å„å­ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’å€‹åˆ¥ã«å‰Šé™¤ã—ã¦ãƒ‡ãƒªã‚²ãƒ¼ãƒˆã‚’é©åˆ‡ã«ã‚¯ãƒªã‚¢
        TArray<UWidget*> ChildWidgets = ItemListScrollBox->GetAllChildren();
        for (UWidget* Child : ChildWidgets)
        {
            if (UMenuItemWidget* MenuItemWidget = Cast<UMenuItemWidget>(Child))
            {
                // æ˜ç¤ºçš„ã«RemoveFromParentã‚’å‘¼ã³å‡ºã—ã¦NativeDestructã‚’ç¢ºå®Ÿã«å®Ÿè¡Œ
                MenuItemWidget->RemoveFromParent();
            }
        }
    }
    ItemListScrollBox->ClearChildren();
    UE_LOG(LogTemp, Warning, TEXT("ğŸ§¹ Cleared existing menu items safely."));

    // å„ã‚¢ã‚¤ãƒ†ãƒ ã«å¯¾ã—ã¦ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚¢ã‚¤ãƒ†ãƒ ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’ä½œæˆ
    for (int32 i = 0; i < Items.Num(); ++i)
    {
        const FInventorySlot& CurrentSlot = Items[i];
        
        // ç©ºã®ã‚¹ãƒ­ãƒƒãƒˆã¯ã‚¹ã‚­ãƒƒãƒ—
        if (CurrentSlot.Count <= 0)
        {
            continue;
        }

        UMenuItemWidget* MenuItemWidget = CreateWidget<UMenuItemWidget>(this, MenuItemWidgetClass);
        if (!MenuItemWidget)
        {
            UE_LOG(LogTemp, Error, TEXT("âŒ Failed to create menu item widget at index %d"), i);
            continue;
        }

        // ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚¢ã‚¤ãƒ†ãƒ ã‚’è¨­å®š
        MenuItemWidget->SetupMenuItem(CurrentSlot, this);
        UE_LOG(LogTemp, Warning, TEXT("âœ… Setup menu item %d: %s (Count: %d)"), 
               i, *CurrentSlot.Item.Name.ToString(), CurrentSlot.Count);

        // ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«ãƒœãƒƒã‚¯ã‚¹ã«è¿½åŠ 
        ItemListScrollBox->AddChild(MenuItemWidget);
    }

    UE_LOG(LogTemp, Warning, TEXT("ğŸ“‹ MenuWidget: Finished setting up inventory"));
}

void UMenuWidget::OnItemSelected(const FInventorySlot& SelectedSlot)
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ¯ Item selected: %s"), *SelectedSlot.Item.Name.ToString());
    
    CurrentSelectedItem = SelectedSlot;

    // è©³ç´°è¡¨ç¤ºã‚¨ãƒªã‚¢ã‚’æ›´æ–°
    if (DetailItemIcon && SelectedSlot.Item.Icon)
    {
        DetailItemIcon->SetBrushFromTexture(SelectedSlot.Item.Icon);
    }

    if (DetailItemName)
    {
        DetailItemName->SetText(SelectedSlot.Item.Name);
    }

    if (DetailItemDescription)
    {
        DetailItemDescription->SetText(SelectedSlot.Item.Description);
    }

    if (DetailItemCount)
    {
        FString CountText = FString::Printf(TEXT("æ‰€æŒæ•°: %d"), SelectedSlot.Count);
        if (SelectedSlot.Item.MaxStack > 1)
        {
            CountText += FString::Printf(TEXT(" / %d"), SelectedSlot.Item.MaxStack);
        }
        DetailItemCount->SetText(FText::FromString(CountText));
    }
}

void UMenuWidget::CloseMenu()
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸšª Closing menu"));
    
    // ã¾ãšã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’å‰Šé™¤
    RemoveFromParent();
    
    // PlayerControllerã¨InputSubsystemã‚’å–å¾—ã—ã¦Input Contextã‚’æ‰‹å‹•ã§åˆ‡ã‚Šæ›¿ãˆ
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PlayerController = World->GetFirstPlayerController())
        {
            // Input Mapping Contextã‚’é€šå¸¸ã«æˆ»ã™
            if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PlayerController->GetLocalPlayer()))
            {
                // ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‹ã‚‰Mapping Contextã‚’å–å¾—
                if (APawn* PlayerPawn = PlayerController->GetPawn())
                {
                    if (ATestHorrorGameCharacter* Character = Cast<ATestHorrorGameCharacter>(PlayerPawn))
                    {
                        // MenuMappingContextã‚’å‰Šé™¤ã—ã¦DefaultMappingContextã‚’è¿½åŠ 
                        if (Character->MenuMappingContext)
                        {
                            Subsystem->RemoveMappingContext(Character->MenuMappingContext);
                        }
                        if (Character->DefaultMappingContext)
                        {
                            Subsystem->AddMappingContext(Character->DefaultMappingContext, 0);
                        }
                        UE_LOG(LogTemp, Warning, TEXT("ğŸ® Switched back to Default Input Context"));
                    }
                }
            }
            
            // ãƒã‚¦ã‚¹ã‚«ãƒ¼ã‚½ãƒ«ã‚’éè¡¨ç¤º
            PlayerController->bShowMouseCursor = false;
            PlayerController->SetInputMode(FInputModeGameOnly());
        }
    }
}

void UMenuWidget::OnCloseButtonClicked()
{
    UE_LOG(LogTemp, Warning, TEXT("ğŸ–±ï¸ Close button clicked"));
    CloseMenu();
}
