#include "MenuItemWidget.h"
#include "Components/Button.h"
#include "Components/Image.h"
#include "Components/TextBlock.h"
#include "MenuWidget.h"
#include "Engine/Texture2D.h"

void UMenuItemWidget::NativeConstruct()
{
    Super::NativeConstruct();
    
    // „Éú„Çø„É≥„ÅÆ„ÇØ„É™„ÉÉ„ÇØ„Ç§„Éô„É≥„Éà„Çí„Éê„Ç§„É≥„Éâ
    if (ItemButton)
    {
        ItemButton->OnClicked.AddDynamic(this, &UMenuItemWidget::OnItemButtonClicked);
    }
}

void UMenuItemWidget::NativeDestruct()
{
    // „Éá„É™„Ç≤„Éº„Éà„ÇíÂÆâÂÖ®„Å´„Ç¢„É≥„Éê„Ç§„É≥„Éâ
    if (ItemButton)
    {
        ItemButton->OnClicked.RemoveAll(this);
    }
    
    // Ë¶™„Å∏„ÅÆÂèÇÁÖß„Çí„ÇØ„É™„Ç¢
    ParentMenuWidget = nullptr;
    
    Super::NativeDestruct();
}

void UMenuItemWidget::SetupMenuItem(const FInventorySlot& SlotData, UMenuWidget* ParentMenu)
{
    ItemSlot = SlotData;
    ParentMenuWidget = ParentMenu;

    UE_LOG(LogTemp, Warning, TEXT("üîß Setting up menu item: %s"), *SlotData.Item.Name.ToString());

    // „Ç¢„Ç§„Ç≥„É≥„ÇíË®≠ÂÆö
    if (ItemIcon && SlotData.Item.Icon)
    {
        ItemIcon->SetBrushFromTexture(SlotData.Item.Icon);
        UE_LOG(LogTemp, Warning, TEXT("‚úÖ Set icon for item: %s"), *SlotData.Item.Name.ToString());
    }
    else if (ItemIcon)
    {
        // „Éá„Éï„Ç©„É´„Éà„Ç¢„Ç§„Ç≥„É≥„Åæ„Åü„ÅØÁ©∫„ÅÆÁä∂ÊÖã
        ItemIcon->SetBrushFromTexture(nullptr);
        UE_LOG(LogTemp, Warning, TEXT("‚ö†Ô∏è No icon available for item: %s"), *SlotData.Item.Name.ToString());
    }

    // „Ç¢„Ç§„ÉÜ„É†Âêç„ÇíË®≠ÂÆö
    if (ItemName)
    {
        ItemName->SetText(SlotData.Item.Name);
    }

    // „Ç¢„Ç§„ÉÜ„É†Êï∞„ÇíË®≠ÂÆö
    if (ItemCount)
    {
        FString CountText = FString::Printf(TEXT("x%d"), SlotData.Count);
        ItemCount->SetText(FText::FromString(CountText));
    }

    UE_LOG(LogTemp, Warning, TEXT("‚úÖ Menu item setup complete: %s (Count: %d)"), 
           *SlotData.Item.Name.ToString(), SlotData.Count);
}

void UMenuItemWidget::OnItemButtonClicked()
{
    UE_LOG(LogTemp, Warning, TEXT("üñ±Ô∏è Menu item clicked: %s"), *ItemSlot.Item.Name.ToString());
    
    if (ParentMenuWidget)
    {
        ParentMenuWidget->OnItemSelected(ItemSlot);
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("‚ùå ParentMenuWidget is null!"));
    }
}
